### ISSUE TITLE
Using two different nav_graph seems to be a bit redundant

### ISSUE THREAD

**Issue by hoangnguyen92dn** [tngcanh07/survey-android#29]
I see you are applying the navigation component with two different graphs: `login_navigation.xml` and `survey_navigation.xml`. My concern is why don't use a single navigation graph for the MainActivity rather than split it into 2 graphs? 🤔

**Comment by tngcanh07** [comment]
the problem is `startDestination`, if user has already logged in, app shows home screen, otherwise, it shows login screen, I don't know how to archive this behavior with 1 nav_graph. do you have better ideas at this point?

but it's fine since we're going to add splash screen. splash will be the startDestination

**Comment by hoangnguyen92dn** [comment]
@tngcanh07 

> do you have better ideas at this point?

From my experience, here are my approaches:
- We would add workaround solution here, use an empty screen for `startDestination` 😄  
- Default `Home` screen is `startDestination` and check if the user logged in before navigating to Login screen (FYI: https://developer.android.com/guide/navigation/navigation-conditional)

> splash will be the startDestination

 Yep. Then you could validate the logged-in status to navigate Home or Login on Splash screen.
